
//LOCATION 
export const SET_LOCATION = "SET_LOCATION"
export const SELECT_LOCATION = "SELECT_LOCATION"
export const CLEAR_LOCATION = "CLEAR_LOCATION"
export const SET_CITY = "SET_CITY"

//WEATHER 
export const CLEAR_WEATHER_DATA = "CLEAR_WEATHER_DATA"
export const SET_WEATHER_DATA = "SET_WEATHER_DATA"

// FETCHING
export const FETCHING = "FETCHING"
export const DONE_FETCHING = "DONE_FETCHING"
export const SET_ERROR = "SET_ERROR"
